# Creatimg DataFrames
Many ways to do it

In [3]:
import numpy as np
import pandas as pd

data=np.random.random(size=(5,3))
print(data)
df =pd.DataFrame(data=data, columns=["A","B","C"])
df


[[0.55808886 0.54486224 0.27816062]
 [0.43124806 0.63002945 0.00805509]
 [0.50032021 0.45170393 0.35609045]
 [0.14568022 0.09950951 0.38723429]
 [0.84745057 0.06422959 0.39287962]]


A         B         C
0  0.558089  0.544862  0.278161
1  0.431248  0.630029  0.008055
2  0.500320  0.451704  0.356090
3  0.145680  0.099510  0.387234
4  0.847451  0.064230  0.392880

In [6]:
df=pd.DataFrame(data={"A":[1,2,3],"B":["Sam","Alex","John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [10]:
dtype=[("A",np.int),("B",(np.str,20))]
data= np.array([(1,"Sam"),(2,"Alex"),(3,"Jhon")],dtype=dtype)
df=pd.DataFrame(data)
df

/tmp/ipykernel_11103/3033002039.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=[("A",np.int),("B",(np.str,20))]
/tmp/ipykernel_11103/3033002039.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=[("A",np.int),("B"

A     B
0  1   Sam
1  2  Alex
2  3  Jhon

In [12]:
data= [{"A":1, "B":"Sam"},{"A":2,"B":"Alex"},{"A":3,"B":"Jhon"}]
df=pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  Jhon